sudo: required
services:
  - docker
language: go
go:
- "1.12.x"
notifications:
  email: false
install:
- true
script:
- "./script/build"
deploy:
- provider: script
  skip_cleanup: true
  script: bash ./script/push-image
  on:
    repo: bakins/php-fpm-exporter
    tags: true
- provider: releases
  skip_cleanup: true
  api_key:
    secure: OAzpeiaXn2K9L1cMMvimprYkxV6fAqAZq5cFdh8vWR/BDfAwMWtqHM7hy9dClVPtMvbAxhhpZn4uO1P9wVdxXn9uxI6Ip8lAZkzDbsgzAfYMmdz4aQI1LJGzBYtKwh8MpQ+hMLiG7UASSH1j3l44e6uckH2rMlwgHsBUq06PstJJTcrR0lP0yd9prHOXhumj++Rr7nJJZvpAEjkRPXb6jKOvd7EyIibL+kjTjWDzDaHNDhrK5GzsKxQoATqL0NuRzK/oL3d1mSrp3zu3odShbnLNSPl8vhg5JPHD+cCGdL2cSw3D3t8WKX7LxJQCeXMF2O7JWh5VSL6QwSp6M+xYjHTQlocmAvvnt8ue/HAuAs2c2WkGxZxB//qURkk2PVkaMK/wOH7w9E1ZMO7jTPcS44nr7EHBLa8IXY2b8/ir6ebJiL2orzbffbKfRWsHbr7IWxY4eWafRouD1UbiB7iX3/cFhGg0HmBa385m+OfFCdbjJn7Lit91k39kaX16O/p1d85mPwLY8HTRpoxln66NWnRtk7kFv5ZJATXyjZ1KAwBgufxLgPBCjfGlOM63POqiyUl49utPwmOF/WUDTsYMxNghpHnOp2kag1mx3//QGZ8CDoZ0hYjGQHE8vbprTUKgXZ6oOS4Uc27Zwp1ifFksZRnTpNzVV9MopMuYQdHiyuc=
  file:
    - php-fpm-exporter.linux.amd64
    - php-fpm-exporter.linux.amd64.sha256.txt
    - php-fpm-exporter.darwin.amd64
    - php-fpm-exporter.darwin.amd64.sha256.txt
  on:
    repo: bakins/php-fpm-exporter
    tags: true
